export default {
  ok: "success",
  classAlready: "class already exist",
  notRegister: "class not register",
  NotFound: " Not Found",
  userLoggedIn: "User logged in",
  incorrectPassword: "incorrect password",
  emailAlready: "email already exist",
  studentDeleted: "Student deleted successfully",
  subjectAlready: "subject already exist",
  teacherDeleted: "teacher deleted successfully",
  notRegister: "student not register",
  teacherLoggedIn: "teacher login successfully",
  studentLoggedIn: "student login successfully",
  updateStudent: "student update successfully",
  updateteacher: "teacher update successfully",
  allSubject: "All subject",
  allStudentes: "All student",
  alluser: "All user",
  allTeacheres: "All teacher",
  allClasses: "All classes",
  createClass: "create class successfully",
  subjectCreate: "create subject successfully",
  teacherCreate: "teacher create successfully",
  studentCreate: "student create successfully",
  userCreate: "user created successfully",
  user_email: "email already exists",
  userUpdate: "user update successfully",
  userDeleted: "user deleted successfully",
  jobAlready: "job aleready exist",
  authorizationError: "You do not have authority to perform this activity",
  createJob: "job created successfully",
  jobDeleted: "job deleted successfully",
  alljob: "get all job successfully",
  createOrder: "order created successfully",
  orderUpdate: "order update successfully",
  orderDeleted: "order delete successfully",
  productCreate: "product create successfully",
  productUpdate: "product update successfully",
  productDeleted: "product delete successfully",
  allProduct: "all product",
  categoryCreate: "create category successfully",
  categoryAlready: "category already exist",
  categoryUpdate: "update category successfylly",
  categoryDeleted: "delete category successfully",
  allcategory: "all category",
  unauthorise: "unauthorise access",
  USER_NOT_FOUND: "user not found",
  AUTHORIZATION_ERROR: "Authorization error",
};
